Repository TheThingsNetwork/lorawan-devices, pull requests merged in 2020-11, with the labels that each got.

#20 Small changes to clarify the example
  README.md
  vendor/example/windsensor-codec.yaml
  vendor/example/windsensor-profile.yaml
Labels: doc, quickfix

#22 doc: Updated vendorProfileID link
  README.md
  vendor/example/windsensor-profile.yaml
Labels: quickfix

#25 Fix Profile IDs for The Things Node to match filenames
  vendor/index.yaml
  vendor/the-things-products/the-things-node.yaml
Labels: bug

#23 Update example file
  vendor/example/windsensor.yaml
Labels: quickfix
